# Generated by Django 4.0 on 2023-03-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=25)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('skills_1', models.CharField(max_length=15)),
                ('skills_2', models.CharField(max_length=15)),
                ('skills_3', models.CharField(blank=True, max_length=15, null=True)),
                ('skills_4', models.CharField(blank=True, max_length=15, null=True)),
                ('skills_5', models.CharField(blank=True, max_length=15, null=True)),
                ('experience_1_title', models.CharField(max_length=20)),
                ('experience_1_duration', models.CharField(max_length=15)),
                ('experience_1_description', models.CharField(max_length=30)),
                ('experience_2_title', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_2_duration', models.CharField(blank=True, max_length=15, null=True)),
                ('experience_2_description', models.CharField(blank=True, max_length=30, null=True)),
                ('experience_3_title', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_3_duration', models.CharField(blank=True, max_length=15, null=True)),
                ('experience_3_description', models.CharField(blank=True, max_length=30, null=True)),
                ('education_1', models.CharField(max_length=30)),
                ('education_1_duration', models.CharField(max_length=15)),
            ],
        ),
    ]
