# Generated by Django 4.0 on 2023-03-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile',
            field=models.CharField(default='', max_length=200),
        ),
    ]
