# Generated by Django 4.0 on 2023-03-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_resume_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills_6',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
