# Generated by Django 4.0 on 2023-03-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_resume_skills_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education_2',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='resume',
            name='education_2_duration',
            field=models.CharField(default='', max_length=15),
        ),
    ]
