# Generated by Django 4.0 on 2023-03-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_resume_education_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education_1_degree',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='resume',
            name='education_2_degree',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_1_organization',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_2_organization',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_3_organization',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
