# Generated by Django 4.0 on 2023-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_resume_education_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education_1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_1_organization',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_1_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_2_organization',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_2_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_3_organization',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience_3_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills_2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills_3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills_4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills_5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills_6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
